---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
cds:
  sql:
    supportedLocales: "*"
sap_document_service:
  enabled: false
  api_url: 
  repository_id: 
  auth_url:
  client_id: 
  client_secret: